coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch: off
comment:
  layout: "header, diff, changes"
codecov:
  max_report_age: off
  require_ci_to_pass: no
